version: '3'

services:
  django:
    build: ./backend
    volumes:
      - uploads:/simstatus/backend/resources/uploads
    networks:
      - nginx_network

  web:
    build: ./web
    volumes:
      - ./web:/web
    networks:
      - nginx_network

  nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - uploads:/www/uploads
    depends_on:
      - django
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  uploads:
