version: '3'

services:
  django:
    build: ./backend
    volumes:
      - uploads:/simstatus/backend/resources/uploads
    networks:
      - nginx_network
    extra_hosts:
      - "db.havek.es:10.0.0.66"

  web:
    build: ./web
    volumes:
      - web:/simstatus/web/dist/simstatus-frontend
    networks:
      - nginx_network

  nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
        - ./etc/nginx/conf.d:/etc/nginx/conf.d
        - uploads:/www/uploads
        - web:/www
    depends_on:
      - django
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  uploads:
  web:
