# Generated by Django 2.2.3 on 2019-07-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0007_auto_20190728_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='installed',
            field=models.BooleanField(default=False),
        ),
    ]
