# Generated by Django 2.2.4 on 2019-08-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0011_auto_20190817_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='simuconf',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
