# Generated by Django 2.2.4 on 2019-08-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0012_simuconf_locked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simuconf',
            old_name='locked',
            new_name='default',
        ),
    ]
