# Generated by Django 2.2.4 on 2019-08-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0013_auto_20190819_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simuconf',
            name='default',
            field=models.NullBooleanField(default=None),
        ),
    ]
